"""[ADD] updated_at, deleted_at and active fields to Note

Revision ID: 1486b35104eb
Revises: 
Create Date: 2024-09-22 10:28:36.654853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1486b35104eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('active')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
