"""[UPDATE] reminder table email and sent

Revision ID: 6e1b683c1a54
Revises: c1ce599cebbc
Create Date: 2024-09-22 21:39:42.985722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1b683c1a54'
down_revision = 'c1ce599cebbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_column('sent')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
